### ISSUE TITLE
Literal path in Cmakelists.txt prevents build

### ISSUE THREAD

**Issue by madskjeldgaard** [hadron-sclang/hadron#58]
Hi Luke
I know it's probably too early to build and test this, but I got curious and tried anyway. Anyway, this line prevents building on other people's machines:

https://github.com/hadron-sclang/hadron/blob/d77848f4edc237c6a79eae9b49ce577b383a846d/third_party/CMakeLists.txt#L46

**Comment by lnihlen** [comment]
Lol whoops! "Tell me you've been working in a vacuum without telling me you've been working in a vacuum."

jemalloc is deprecated anyway, I'll clean that up shortly, thanks.

**Comment by lnihlen** [comment]
#59 deprecates jemalloc and so this line is removed in main.

**Comment by madskjeldgaard** [comment]
Thanks! Will test again

--
Best regards, Mads Kjeldgaard
